### ISSUE TITLE
Privacy  Policy Website

### ISSUE THREAD

**Issue by sonydei** [chankruze/WhatsApp-Stickers#2]
How could it be done instead of a url for the privacy files to do it in local?

**Comment by chankruze** [comment]
You can add a folder to assets folder.Then update the url in contents.json pointing out to that local folder privacy files and let me know.

The same can be done for changelog also.
**Edit:**
You can look into MX Player, it uses same method local html site to show contributers and changelogs and policy.
Tell me if this is solved so i can close the issue.
